In [1]:
import pandas as pd

df= pd.read_csv(r'C:\Users\Dilshani\Documents\F1_project\data\raw\podium_prediction_dataset.csv')

df.describe()

C:\Users\Dilshani\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,raceId,year,round,resultId,driverId,constructorId,qualifying_position,best_quali_ms,qualifying_gap_to_pole_ms,teammate_qualifying_gap_ms,...,constructor_points_last_5,constructor_podium_rate_last_5,avg_pit_ms_last_5,pit_consistency_last_5,total_pit_stops_last_5,driver_dnf_rate_last_10,constructor_dnf_rate_last_20,finish_position,points,podium_finish
count,84986.000000,84986.000000,84986.000000,84986.000000,84986.000000,84986.000000,7805.000000,7805.000000,7805.000000,7805.000000,...,83914.000000,83914.000000,24684.000000,24684.000000,24724.000000,80973.000000,84617.000000,84986.000000,84986.000000,84986.000000
mean,644.280576,1979.075095,6.772515,15712.837726,381.921587,68.400537,5.377578,87120.299295,949.505445,0.000000,...,30.203267,0.751339,34355.618907,34355.618907,17.575756,0.450400,0.439318,12.949321,1.532172,0.119243
std,279.500697,23.968325,5.018951,6901.040572,270.696911,61.645913,2.825487,12200.238955,1136.700542,464.312237,...,33.099902,0.920358,80811.004539,80811.004539,4.935326,0.271585,0.213897,7.779152,3.754040,0.324076
min,1.000000,1950.000000,1.000000,1.000000,1.000000,1.000000,1.000000,53377.000000,0.000000,-10033.500000,...,0.000000,0.000000,2.121320,2.121320,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,439.000000,1955.000000,2.000000,10805.000000,119.000000,9.000000,3.000000,76992.000000,328.000000,-75.000000,...,4.000000,0.000000,1421.836623,1421.836623,14.000000,0.200000,0.300000,7.000000,0.000000,0.000000
50%,760.000000,1975.000000,6.000000,18640.000000,385.000000,49.000000,5.000000,86869.000000,771.000000,0.000000,...,20.140000,0.400000,2620.498472,2620.498472,17.000000,0.428571,0.450000,12.000000,0.000000,0.000000
75%,809.000000,2000.000000,10.000000,20218.000000,608.000000,113.000000,8.000000,95134.000000,1312.000000,75.000000,...,46.000000,1.200000,7465.445296,7465.445296,21.000000,0.625000,0.600000,19.000000,1.000000,0.000000
max,1172.000000,2026.000000,24.000000,27331.000000,866.000000,217.000000,16.000000,129776.000000,31189.000000,10033.500000,...,222.000000,3.200000,708754.483946,708754.483946,34.000000,1.000000,1.000000,39.000000,50.000000,1.000000

In [2]:
import sys
sys.path.append('../src')

from preprocessing import preprocess_data

df = preprocess_data(df)

In [3]:
df.head(10)

,raceId,year,round,race_name,race_date,resultId,driverId,constructorId,driver_name,constructor_name,...,podium_finish,race_month,race_dayofweek,grid_missing_flag,qualifying_position_missing,qualifying_gap_to_pole_ms_missing,avg_finish_last_5_missing,constructor_avg_finish_last_5_missing,avg_pit_ms_last_5_missing,driver_dnf_rate_last_10_missing
0,1,2009,1,Australian Grand Prix,2009-03-29,7556,15,7,Jarno Trulli,Toyota,...,1,3,6,False,0,0,0,0,0,0
1,1,2009,1,Australian Grand Prix,2009-03-29,7556,15,7,Jarno Trulli,Toyota,...,1,3,6,False,0,0,0,0,0,0
2,1,2009,1,Australian Grand Prix,2009-03-29,7557,10,7,Timo Glock,Toyota,...,0,3,6,False,0,0,0,0,0,0
3,1,2009,1,Australian Grand Prix,2009-03-29,7557,10,7,Timo Glock,Toyota,...,0,3,6,False,0,0,0,0,0,0
4,2,2009,2,Malaysian Grand Prix,2009-04-05,7577,15,7,Jarno Trulli,Toyota,...,0,4,6,False,0,0,0,0,0,0
5,2,2009,2,Malaysian Grand Prix,2009-04-05,7577,15,7,Jarno Trulli,Toyota,...,0,4,6,False,0,0,0,0,0,0
6,2,2009,2,Malaysian Grand Prix,2009-04-05,7576,10,7,Timo Glock,Toyota,...,1,4,6,False,0,0,0,0,0,0
7,2,2009,2,Malaysian Grand Prix,2009-04-05,7576,10,7,Timo Glock,Toyota,...,1,4,6,False,0,0,0,0,0,0
8,3,2009,3,Chinese Grand Prix,2009-04-19,7602,4,4,Fernando Alonso,Renault,...,0,4,6,False,0,0,0,0,0,0
9,3,2009,3,Chinese Grand Prix,2009-04-19,7602,4,4,Fernando Alonso,Renault,...,0,4,6,False,0,0,0,0,0,0

In [4]:
df.isnull().sum()

raceId                                   0
year                                     0
round                                    0
race_name                                0
race_date                                0
resultId                                 0
driverId                                 0
constructorId                            0
driver_name                              0
constructor_name                         0
grid                                     0
qualifying_position                      0
best_quali_ms                            0
qualifying_gap_to_pole_ms                0
teammate_qualifying_gap_ms               0
avg_finish_last_5                        0
podiums_last_5                           0
avg_qualifying_last_5                    0
dnf_rate_last_10                         0
constructor_avg_finish_last_5            0
constructor_points_last_5                0
constructor_podium_rate_last_5           0
avg_pit_ms_last_5                        0
pit_consistency_last_5                   0
total_pit_stops_last_5                   0
driver_dnf_rate_last_10                  0
constructor_dnf_rate_last_20             0
finish_position                          0
points                                   0
podium_finish                            0
race_month                               0
race_dayofweek                           0
grid_missing_flag                        0
qualifying_position_missing              0
qualifying_gap_to_pole_ms_missing        0
avg_finish_last_5_missing                0
constructor_avg_finish_last_5_missing    0
avg_pit_ms_last_5_missing                0
driver_dnf_rate_last_10_missing          0
dtype: int64

In [5]:
import sys
sys.path.append(r"C:\Users\Dilshani\Documents\F1_project\src")
from predict import make_predictions
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Dilshani\Documents\F1_project\data\raw\podium_prediction_dataset.csv"
)

predicted_df = make_predictions(df)

predicted_df.head()

C:\Users\Dilshani\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

ImportError: cannot import name 'issparse' from 'scipy.sparse' (unknown location)

In [6]:
import sklearn
import scipy
import numpy

print("sklearn:", sklearn.__version__)
print("scipy:", scipy.__version__)
print("numpy:", numpy.__version__)

ImportError: cannot import name 'issparse' from 'scipy.sparse' (unknown location)